app = 'growbro-worker'  # Change to your unique Fly app name
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '8gb'
  cpu_kind = 'performance'
  cpus = 1
  memory_mb = 8192
