app = 'growbro-worker'  # Change to your unique Fly app name
primary_region = 'lhr'



[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'  # Stop machines when not in use to save costs
  auto_start_machines = true
  min_machines_running = 0  # Allow full shutdown when no signups

[[vm]]
  memory = '8gb'  # Scale memory with CPU count
  cpu_kind = 'performance'
  cpus = 1  # Double the processing power for parallel operations
  memory_mb = 8192

