app = 'growbro-worker'  # Change to your unique Fly app name
primary_region = 'lhr'

# Add swap space for memory spikes during large document processing
swap_size_mb = 2048

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'  # Stop machines when not in use to save costs
  auto_start_machines = true
  min_machines_running = 0  # Allow full shutdown when no signups

[[vm]]
  memory = '16gb'  # Scale memory with CPU count
  cpu_kind = 'performance'
  cpus = 2  # Double the processing power for parallel operations
  memory_mb = 16384

[env]
  # Python and numerical computation optimizations
  PYTHONUNBUFFERED = "1"
  OMP_NUM_THREADS = "2"  # Match CPU count
  NUMEXPR_MAX_THREADS = "2"
  TOKENIZERS_PARALLELISM = "true"
